steps:
  - name: "hashicorp/terraform:1.6.6"
    id: Init
    entrypoint: /bin/sh
    args:
      - -c
      - |
        terraform init

  - name: "hashicorp/terraform:1.6.6"
    id: Validate
    entrypoint: /bin/sh
    args:
      - -c
      - |
        terraform validate

  - name: "hashicorp/terraform:1.6.6"
    id: Plan
    entrypoint: /bin/sh
    args:
      - -c
      - |
        terraform plan -var-file="terraform.tfvars" -out=tfplan

  - name: "hashicorp/terraform:1.6.6"
    id: Apply
    entrypoint: /bin/sh
    args:
      - -c
      - |
        terraform apply -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
